# Generated by Django 4.2 on 2023-09-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('query_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('IN-PERSON', 'In-Person')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=100)),
                ('product_category_image', models.ImageField(blank=True, upload_to='product_category')),
                ('product_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_short_description', models.CharField(blank=True, max_length=200)),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_discount_price', models.PositiveIntegerField(blank=True)),
                ('product_price', models.PositiveIntegerField()),
                ('product_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory')),
            ],
        ),
    ]
